# Generated by Django 3.2.18 on 2023-03-13 12:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230313_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comments',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='comment', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], default='Male', max_length=200),
        ),
    ]
