# Generated by Django 3.2.18 on 2023-03-14 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230313_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], default='Male', max_length=200),
        ),
    ]
