# Generated by Django 3.2.18 on 2023-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20230315_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Others', 'Others'), ('Male', 'Male')], default='Male', max_length=200),
        ),
    ]
