# Generated by Django 3.2.18 on 2023-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230315_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/images'),
        ),
    ]
