# Generated by Django 3.2.18 on 2023-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20230315_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Others', 'Others'), ('Male', 'Male')], default='Male', max_length=200),
        ),
    ]
